### PR TITLE
Added random Dice Simulator in python

### PR DESCRIPTION
**Pull request by amitShindeGit**
A random dice simulator in python.

### CODE REVIEW

**Comment by amitShindeGit** [comment]
I am confused, what are these?

**Review by Iltwats — CHANGES_REQUESTED** [review]
Please provide appropriate info about your program inside the file.

**Comment by Iltwats** [comment]
> I am confused, what are these checks?

These are branch protection rule enforced to keep main branch safe from spam PRs.

**Comment by amitShindeGit** [comment]
Hey, i have provided info about how my code works inside the same file. Kindly check it and tell me if anything else needs to be done.

**Review by Iltwats — APPROVED** [review]

**Pull request merged**
